### ISSUE TITLE
Incompatible with the sodium 1.16.x/next branch

### ISSUE THREAD

**Issue by coderbot16** [PepperCode1/Item-Model-Fix#1] opened 2020-12-30 03:10 UTC
> [22:03:44] [main/FATAL]: Mixin apply failed itemmodelfix.mixins.json:SodiumFluidRendererMixin -> me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyConstant annotation on onRender0 could not find any targets matching 'render(Lnet/minecraft/class_1920;Lnet/minecraft/class_3610;Lnet/minecraft/class_2338;Lme/jellysquid/mods/sodium/client/model/quad/sink/ModelQuadSinkDelegate;)Z' in me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer. Using refmap item-model-fix-refmap.json [PREINJECT Applicator Phase -> itemmodelfix.mixins.json:SodiumFluidRendererMixin -> Prepare Injections ->  -> constant$ckj000$onRender0(F)F -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyConstant annotation on onRender0 could not find any targets matching 'render(Lnet/minecraft/class_1920;Lnet/minecraft/class_3610;Lnet/minecraft/class_2338;Lme/jellysquid/mods/sodium/client/model/quad/sink/ModelQuadSinkDelegate;)Z' in me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer. Using refmap item-model-fix-refmap.json [PREINJECT Applicator Phase -> itemmodelfix.mixins.json:SodiumFluidRendererMixin -> Prepare Injections ->  -> constant$ckj000$onRender0(F)F -> Parse]

**Comment by PepperCode1** [comment] 2020-12-30 04:37
This issue is caused by the "fix fluid rendering" option in the config when it is set to true because it is mixing directly into one of Sodium's class that changed during the development of 0.1.1. It can be turned off by editing the config json or starting Minecraft without Sodium and accessing the config screen. I might not fix this right now as the option is marked as experimental and doesn't even work that well (fixes one problem, but causes another that is just as big). Also, Sodium 0.1.1 isn't fully released yet so if I make a new mixin for the current latest it might change again before the release. That said, I might look into improving the option so that it is actually worth using.

**Comment by PepperCode1** [comment] 2021-01-10 21:44
The latest commit has solved this issue by removing the option all together. The reasons as to why this was done are listed in the commit description.

**Closed by PepperCode1** 2021-01-10 21:44 UTC
Labels: bug

**Comment by Kichura** [comment] 2021-01-24 02:27
I could not reproduce this in 1.16.5 even with fluid rendering enabled, However the issue does appear in snapshot releases so going to assume video API changed perhaps?

**Comment by PepperCode1** [comment] 2021-01-24 02:57
Yes. The mixin in this mod that "fixed" the fluid rendering in Sodium could not find the class because it did not exist anymore and this caused Minecraft to crash. There are ways to make it so this does not cause a crash but I decided to remove the option instead.
